services:
  - type: web
    name: business-card-api
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      apt-get install -y libtesseract-dev
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: MONGO_URI
        sync: false
      - key: TESSERACT_PATH
        sync: false
